name: CI deployment

on:
  push:
#    Uncomment line 7 and remove line 8 and 9,
#    for enable this action.
#    branches: [master]
    branches-ignore:
      - '**'

jobs:
  deploy_project:
    name: Build and deploy project
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just_a_placeholder_to_avoid_errors'
      - name: Adding know hosts
        run: ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
      - name: Build project
        run: NODE_ENV=production yarn build
      - name: Rsync project with server one
        run: rsync -r --exclude="config/database.js" . ${{ secrets.STAGING_SERVER }}:${{ secrets.STAGING_PROJECT_FOLDER }}
      - name: Restart server
        run: ssh ${{ secrets.STAGING_SERVER }} pm2 reload ${{ secrets.PROCESS_NAME }}
